### ISSUE TITLE
Wrong module path

### ISSUE THREAD

**Issue by hasit** [thediveo/noleak#1]
@TheDiveO 

Hello, thank you for working on this. I am very excited to use `noleak` to find goroutine leaks.

When `go get`ing `noleak`, I see the following error:

```
$ go get github.com/TheDiveO/noleak@latest
go: github.com/TheDiveO/noleak@v0.1.0: parsing go.mod:
	module declares its path as: github.com/thediveo/noleak
	        but was required as: github.com/TheDiveO/noleak
```

**Comment by thediveo** [comment]
please go-get it with lower case `thediveo`. I "like" GitHub for this feature of upper-casing...

**Comment by thediveo** [comment]
I've finally bit the bullet and renamed my user to all-lowercase "thediveo", thus people taking the straightforward path of copying and pasting the repo URL and then removing `https://` shouldn't get bitten in the future anymore. This should fix your problem so I will close this issue; if there are still problems then please don't hesitate to reopen this issue or drop here a notice that there's something else not working correctly.

**Comment by hasit** [comment]
Thank you, @thediveo
